### ISSUE TITLE
Main (landing) page

### ISSUE THREAD

**Issue by rychkog** [Gapminder/gapminder-org#3]
- [ ] "Slider" section ( refs #4 )
- [ ] "Latest Videos" section ( refs #5 )
- [ ] "Latest Blog Posts" section ( refs #6 )
- [ ] "Hans Tweets" section ( refs #7 )
- [ ] "Header" section ( refs #8 )
- [ ] "Footer" section ( refs #9 )
