### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by natali-abyss** [Gapminder/gapminder-org#68]
- [x] Investigate different approaches to express breadcrumbs in contentful data structures ( refs #69 )
- [x] Create structure that express breadcrumbs  ( refs #70 )
- [x] Change current contentful gapminder.org UI to support new data structure ( refs #71 )
