### ISSUE TITLE
Breadcrumbs: Change current contentful gapminder.org UI to support new data structure 

### ISSUE THREAD

**Issue by natali-abyss** [Gapminder/gapminder-org#71]
- [ ] Modify ContentfulContentService to be able to work with new structures ( refs #72 )
- [ ] Render menu using new structures ( refs #73  )
- [ ] Make menu items navigable ( refs #74 )
- [ ] Render NodePage with regard to breadcrumbs data structure ( refs #75 )
